/**
 * @file Heuristics for client-side video classification.
 */

// Keyword-based heuristics
const POSITIVE_KEYWORDS = [
  'tutorial', 'how-to', 'lecture', 'documentary', 'science', 'math',
  'history', 'programming', 'course', 'lesson', 'explanation', 'review',
  'analysis', 'biography', 'experiment', 'workshop', 'training',
  'seminar', 'webinar', 'guide', 'build', 'develop', 'design',
  'astronomy', 'biology', 'chemistry', 'physics', 'engineering',
  'technology', 'psychology', 'sociology', 'economics', 'politics',
  'philosophy', 'art history', 'music theory', 'linguistics',
  'geography', 'geology', 'paleontology', 'archaeology', 'anatomy',
  'physiology', 'genetics', 'evolution', 'ecology', 'botany', 'zoology',
  'mycology', 'entomology', 'ornithology', 'herpetology', 'ichthyology',
  'mammalogy', 'primatology', 'anthropology', 'criminology', 'pedagogy',
  'andragogy', 'epistemology', 'ontology', 'metaphysics', 'ethics',
  'aesthetics', 'logic', 'rhetoric', 'grammar', 'literature', 'poetry',
  'prose', 'fiction', 'non-fiction', 'memoir', 'autobiography',
  'journalism', 'calligraphy', 'typography', 'photography',
  'cinematography', 'film studies', 'media studies', 'communication',
  'journalism', 'marketing', 'business', 'finance', 'accounting',
  'investing', 'entrepreneurship', 'management', 'leadership',
  'productivity', 'organization', 'planning', 'strategy', 'negotiation',
  'public speaking', 'debate', 'critical thinking', 'problem solving',
  'creativity', 'innovation', 'collaboration', 'teamwork', 'leadership',
  'emotional intelligence', 'mindfulness', 'meditation', 'yoga',
  'nutrition', 'fitness', 'health', 'wellness', 'first aid',
  'emergency preparedness', 'survival skills', 'gardening', 'cooking',
  'baking', 'brewing', 'winemaking', 'distilling', 'fermentation',
  'canning', 'preserving', 'woodworking', 'metalworking', 'blacksmithing',
  'welding', 'machining', 'fabrication', 'electronics', 'robotics',
  'automation', 'mechatronics', 'cybernetics', 'nanotechnology',
  'biotechnology', 'bioinformatics', 'bioengineering', 'biomedical',
  'biophysics', 'biochemistry', 'neuroscience', 'cognitive science',
  'computer science', 'software engineering', 'data science',
  'machine learning', 'artificial intelligence', 'deep learning',
  'neural networks', 'natural language processing', 'computer vision',
  'computer graphics', 'game development', 'web development',
  'mobile development', 'database administration', 'system administration',
  'network administration', 'cybersecurity', 'information security',
  'ethical hacking', 'penetration testing', 'digital forensics',
  'cryptography', 'blockchain', 'quantum computing', 'cloud computing',
  'devops', 'site reliability engineering', 'agile', 'scrum', 'kanban',
  'lean', 'six sigma', 'project management', 'product management',
  'user experience', 'user interface', 'interaction design',
  'visual design', 'graphic design', 'industrial design',
  'architectural design', 'interior design', 'fashion design',
  'costume design', 'set design', 'sound design', 'lighting design',
  'game design', 'level design', 'narrative design', 'system design',
  'instructional design', 'curriculum design', 'e-learning',
  'blended learning', 'online learning', 'distance learning',
  'mobile learning', 'microlearning', 'gamification', 'simulation',
  'virtual reality', 'augmented reality', 'mixed reality',
  'extended reality', 'haptics', 'robotics', 'drones',
  '3d printing', 'laser cutting', 'cnc machining', 'waterjet cutting',
  'plasma cutting', 'welding', 'soldering', 'brazing', 'casting',
  'forging', 'molding', 'injection molding', 'extrusion',
  'thermoforming', 'vacuum forming', 'rotational molding',
  'blow molding', 'compression molding', 'transfer molding',
  'laminating', 'pultrusion', 'filament winding', 'resin infusion',
  'autoclave', 'composite materials', 'carbon fiber', 'fiberglass',
  'kevlar', 'aramid', 'dyneema', 'spectra', 'zylon', 'vectran',
  'technora', 'twaron', 'nomex', 'polycarbonate', 'abs', 'pla',
  'petg', 'nylon', 'tpu', 'tpe', 'pvc', 'hdpe', 'ldpe', 'pp', 'ps',
  'pmma', 'acrylic', 'polyurethane', 'silicone', 'epoxy', 'resin',
  'concrete', 'cement', 'mortar', 'grout', 'plaster', 'stucco',
  'adobe', 'rammed earth', 'cob', 'straw bale', 'bamboo', 'wood',
  'timber', 'lumber', 'plywood', 'osb', 'mdf', 'particle board',
  'hardboard', 'cork', 'balsa', 'bamboo', 'rattan', 'willow',
  'wicker', 'seagrass', 'jute', 'hemp', 'sisal', 'coir', 'abaca',
  'ramie', 'flax', 'linen', 'cotton', 'wool', 'silk', 'cashmere',
  'mohair', 'angora', 'alpaca', 'llama', 'vicuna', 'guanaco',
  'muskox', 'qiviut', 'yak', 'camel', 'bison', 'leather', 'suede',
  'nubuck', 'fur', 'felt', 'nonwoven', 'geotextile', 'agrotextile',
  'medtextile', 'protech', 'sporttech', 'buildtech', 'hometech',
  'clothtech', 'indutech', 'mobiltech', 'oekotech', 'packtech',
  'geology', 'geography', 'meteorology', 'oceanography',
  'climatology', 'hydrology', 'limnology', 'glaciology',
  'geomorphology', 'pedology', 'edaphology', 'geodesy',
  'photogrammetry', 'cartography', 'gis', 'remote sensing',
  'gps', 'galileo', 'glonass', 'beidou', 'irnss', 'qzss',
  'space exploration', 'rocketry', 'spacecraft', 'satellite',
  'space station', 'space telescope', 'rover', 'lander', 'probe',
  'astronaut', 'cosmonaut', 'taikonaut', 'vyomanaut',
  'space tourism', 'space colonization', 'terraforming',
  'astrobiology', 'exobiology', 'xenobiology', 'astrochemistry',
  'astroparticle physics', 'cosmology', 'astrophysics',
  'planetary science', 'solar physics', 'stellar astronomy',
  'galactic astronomy', 'extragalactic astronomy',
  'observational astronomy', 'theoretical astronomy',
  'computational astronomy', 'archaeoastronomy', 'astroinformatics',
  'astrometry', 'photometry', 'spectroscopy', 'polarimetry',
  'interferometry', 'helioseismology', 'asteroseismology',
  'gravitational wave astronomy', 'neutrino astronomy',
  'high-energy astronomy', 'x-ray astronomy', 'gamma-ray astronomy',
  'uv astronomy', 'infrared astronomy', 'radio astronomy',
  'submillimeter astronomy', 'terahertz astronomy',
  'far-infrared astronomy', 'microwave astronomy',
  'amateur astronomy', 'citizen science', 'outreach',
  'public engagement', 'science communication', 'stem', 'steam',
  'maker culture', 'diy', 'hobby', 'craft', 'skill', 'trade',
  'vocation', 'profession', 'career', 'job', 'work', 'employment',
  'internship', 'apprenticeship', 'mentorship', 'coaching',
  'counseling', 'therapy', 'rehabilitation', 'recovery',
  'support group', 'community', 'volunteering', 'activism',
  'advocacy', 'charity', 'philanthropy', 'fundraising',
  'nonprofit', 'ngo', 'social enterprise', 'cooperative',
  'credit union', 'mutual', 'benefit corporation', 'b corp',
  'fair trade', 'ethical sourcing', 'sustainability',
  'renewable energy', 'energy conservation', 'waste reduction',
  'recycling', 'composting', 'upcycling', 'circular economy',
  'green building', 'sustainable agriculture', 'permaculture',
  'agroforestry', 'hydroponics', 'aquaponics', 'aeroponics',
  'vertical farming', 'indoor farming', 'precision agriculture',
  'regenerative agriculture', 'organic farming', 'biodynamic',
  'natural farming', 'conservation', 'restoration', 'rewilding',
  'reforestation', 'afforestation', 'watershed management',
  'wetland restoration', 'coral reef restoration',
  'mangrove restoration', 'seagrass restoration',
  'prairie restoration', 'forest restoration',
  'habitat restoration', 'wildlife conservation',
  'endangered species', 'biodiversity', 'ecosystem',
  'ecology', 'environmental science', 'climate science',
  'earth science', 'planetary science', 'space science',
  'rocket science', 'nuclear science', 'particle physics',
  'quantum mechanics', 'relativity', 'string theory',
  'm-theory', 'loop quantum gravity', 'supersymmetry',
  'dark matter', 'dark energy', 'black hole', 'neutron star',
  'white dwarf', 'red giant', 'supernova', 'nebula',
  'galaxy', 'quasar', 'pulsar', 'magnetar', 'blazar',
  'active galactic nucleus', 'cosmic microwave background',
  'big bang', 'inflation', 'multiverse', 'wormhole',
  'time travel', 'faster-than-light', 'warp drive',
  'generation ship', 'interstellar travel', 'intergalactic travel',
  'extraterrestrial life', 'alien', 'ufo', 'uap',
  'seti', 'meti', 'fermi paradox', 'drake equation',
  'great filter', 'kardashev scale', 'dyson sphere',
  'matrioshka brain', 'jupiter brain', 'computronium',
  'technosignature', 'biosignature', 'archaeology',
  'paleontology', 'anthropology', 'sociology', 'psychology',
  'economics', 'political science', 'history', 'philosophy',
  'linguistics', 'semiotics', 'hermeneutics', 'phenomenology',
  'existentialism', 'stoicism', 'epicureanism', 'cynicism',
  'skepticism', 'platonism', 'aristotelianism', 'empiricism',
  'rationalism', 'idealism', 'materialism', 'dualism',
  'monism', 'nihilism', 'absurdism', 'utilitarianism',
  'deontology', 'virtue ethics', 'consequentialism',
  'contractualism', 'egalitarianism', 'libertarianism',
  'socialism', 'communism', 'anarchism', 'fascism',
  'capitalism', 'democracy', 'republic', 'monarchy',
  'oligarchy', 'autocracy', 'theocracy', 'plutocracy',
  'kleptocracy', 'gerontocracy', 'technocracy', 'meritocracy',
  'anarchy', 'geopolitics', 'international relations',
  'foreign policy', 'diplomacy', 'war', 'peace', 'conflict',
  'terrorism', 'espionage', 'intelligence', 'counterintelligence',
  'propaganda', 'disinformation', 'misinformation', 'fake news',
  'media literacy', 'digital literacy', 'information literacy',
  'financial literacy', 'health literacy', 'civic literacy',
  'legal literacy', 'scientific literacy', 'data literacy',
  'statistical literacy', 'emotional literacy', 'social literacy',
  'cultural literacy', 'visual literacy', 'media literacy',
  'news literacy', 'algorithmic literacy', 'coding literacy',
  'computational thinking', 'design thinking', 'systems thinking',
  'futures thinking', 'strategic thinking', 'ethical thinking',
  'empathy', 'compassion', 'kindness', 'gratitude', 'forgiveness',
  'resilience', 'grit', 'perseverance', 'self-control',
  'self-regulation', 'self-awareness', 'self-esteem',
  'self-confidence', 'self-efficacy', 'self-compassion',
  'self-care', 'mental health', 'emotional health',
  'physical health', 'social health', 'spiritual health',
  'environmental health', 'occupational health',
  'financial health', 'intellectual health', 'creative health',
  'personal development', 'professional development',
  'skill development', 'career development', 'leadership development',
  'organizational development', 'community development',
  'sustainable development', 'human development',
  'child development', 'adolescent development',
  'adult development', 'gerontology', 'aging', 'longevity',
  'life extension', 'transhumanism', 'posthumanism',
  'biohacking', 'nootropics', 'quantified self',
  'wearable technology', 'implantable technology',
  'brain-computer interface', 'neural lace', 'mind uploading',
  'cryonics', 'cryopreservation', 'vitrification',
  'nanomedicine', 'regenerative medicine', 'gene therapy',
  'stem cell therapy', 'cloning', 'tissue engineering',
  '3d bioprinting', 'synthetic biology', 'xenotransplantation',
  'personalized medicine', 'precision medicine', 'genomic medicine',
  'pharmacogenomics', 'proteomics', 'metabolomics',
  'lipidomics', 'glycomics', 'transcriptomics', 'epigenomics',
  'microbiomics', 'connectomics', 'toxicogenomics',
  'nutrigenomics', 'immunogenomics', 'cancer genomics',
  'cardiovascular genomics', 'neurogenomics', 'psychiatric genomics',
  'behavioral genomics', 'population genomics', 'evolutionary genomics',
  'comparative genomics', 'functional genomics', 'structural genomics',
  'metagenomics', 'paleogenomics', 'archaeogenomics',
  'environmental genomics', 'forensic genomics', 'consumer genomics',
  'recreational genomics', 'genomic privacy', 'genomic ethics',
  'genomic law', 'genomic policy', 'genomic data sharing',
  'genomic standards', 'genomic education', 'genomic literacy',
  'genomic counseling', 'genetic counseling', 'genetic testing',
  'genetic screening', 'newborn screening', 'carrier screening',
  'prenatal screening', 'preimplantation genetic diagnosis',
  'predictive testing', 'diagnostic testing', 'pharmacogenetic testing',
  'nutrigenetic testing', 'ancestry testing', 'relationship testing',
  'forensic testing', 'research testing', 'direct-to-consumer',
  'clinical', 'laboratory', 'hospital', 'clinic', 'doctor',
  'physician', 'surgeon', 'nurse', 'practitioner', 'assistant',
  'therapist', 'counselor', 'psychologist', 'psychiatrist',
  'pharmacist', 'dietitian', 'nutritionist', 'physical therapist',
  'occupational therapist', 'speech therapist', 'respiratory therapist',
  'radiologic technologist', 'medical laboratory scientist',
  'phlebotomist', 'paramedic', 'emt', 'firefighter', 'police',
  'military', 'veteran', 'lawyer', 'judge', 'paralegal',
  'court reporter', 'detective', 'investigator', 'forensic scientist',
  'crime scene investigator', 'coroner', 'medical examiner',
  'teacher', 'professor', 'instructor', 'lecturer', 'tutor',
  'coach', 'mentor', 'librarian', 'archivist', 'curator',
  'museum', 'gallery', 'exhibit', 'conservator', 'restorer',
  'historian', 'archaeologist', 'anthropologist', 'sociologist',
  'psychologist', 'economist', 'political scientist', 'philosopher',
  'theologian', 'ethicist', 'linguist', 'translator',
  'interpreter', 'writer', 'author', 'editor', 'publisher',
  'journalist', 'reporter', 'correspondent', 'anchor',
  'producer', 'director', 'cinematographer', 'editor',
  'sound designer', 'composer', 'musician', 'singer',
  'songwriter', 'conductor', 'arranger', 'producer',
  'dj', 'vj', 'artist', 'painter', 'sculptor', 'illustrator',
  'animator', 'designer', 'photographer', 'choreographer',
  'dancer', 'actor', 'comedian', 'magician', 'illusionist',
  'juggler', 'acrobat', 'clown', 'mime', 'puppeteer',
  'ventriloquist', 'storyteller', 'poet', 'novelist',
  'playwright', 'screenwriter', 'cartoonist', 'calligrapher',
  'typographer', 'architect', 'engineer', 'scientist',
  'mathematician', 'statistician', 'actuary', 'data scientist',
  'analyst', 'researcher', 'developer', 'programmer',
  'administrator', 'manager', 'executive', 'entrepreneur',
  'investor', 'trader', 'broker', 'agent', 'consultant',
  'advisor', 'planner', 'strategist', 'organizer',
  'coordinator', 'facilitator', 'mediator', 'negotiator',
  'arbitrator', 'advocate', 'activist', 'organizer',
  'volunteer', 'philanthropist', 'humanitarian',
  'environmentalist', 'conservationist', 'restorationist',
  'educator', 'learner', 'student', 'scholar', 'academic',
  'intellectual', 'polymath', 'autodidact', 'bibliophile',
  'philosopher', 'theologian', 'mystic', 'guru', 'sage',
  'shaman', 'priest', 'rabbi', 'imam', 'pastor', 'monk',
  'nun', 'yogi', 'swami', 'lama', 'roshi', 'sensei',
  'master', 'adept', 'initiate', 'disciple', 'apprentice',
  'follower', 'devotee', 'believer', 'pilgrim', 'seeker',
  'skeptic', 'agnostic', 'atheist', 'humanist', 'freethinker',
  'rationalist', 'empiricist', 'materialist', 'naturalist',
  'secularist', 'objectivist', 'transcendentalist',
  'romantic', 'modernist', 'postmodernist', 'surrealist',
  'dadaist', 'cubist', 'futurist', 'impressionist',
  'expressionist', 'fauvist', 'symbolist', 'realist',
  'naturalist', 'neoclassicist', 'baroque', 'rococo',
  'renaissance', 'gothic', 'romanesque', 'byzantine',
  'islamic', 'indian', 'chinese', 'japanese', 'korean',
  'african', 'oceanic', 'native american', 'mesoamerican',
  'andean', 'egyptian', 'mesopotamian', 'persian',
  'greek', 'roman', 'celtic', 'norse', 'slavic',
  'germanic', 'latin', 'sanscrit', 'hebrew', 'arabic',
  'chinese', 'japanese', 'korean', 'vietnamese',
  'thai', 'hindi', 'bengali', 'punjabi', 'marathi',
  'telugu', 'tamil', 'kannada', 'malayalam', 'gujarati',
  'odia', 'assamese', 'nepali', 'sinhala', 'urdu',
  'pashto', 'farsi', 'kurdish', 'turkish', 'azerbaijani',
  'uzbek', 'kazakh', 'kyrgyz', 'turkmen', 'tatar',
  'bashkir', 'chuvash', 'mongolian', 'buryat', 'kalmyk',
  'tibetan', 'dzongkha', 'burmese', 'khmer', 'lao',
  'mon', 'shan', 'karen', 'hmong', 'mien', 'zhuang',
  'buyi', 'dong', 'yi', 'nosu', 'li', 'hani', 'lisu',
  'lahu', 'akha', 'wa', 'palaung', 'blang', 'gin',
  'miao', 'yao', 'she', 'tujia', 'gelao', 'mulam',
  'maonan', 'qiang', 'pumi', 'naxi', 'lisu', 'nu',
  'drung', 'jingpo', 'deang', 'bonan', 'dongxiang',
  'salar', 'yugur', 'uyghur', 'tatar', 'russian',
  'ukrainian', 'belarusian', 'polish', 'czech', 'slovak',
  'hungarian', 'romanian', 'bulgarian', 'serbian',
  'croatian', 'bosnian', 'montenegrin', 'macedonian',
  'slovenian', 'albanian', 'greek', 'armenian',
  'georgian', 'chechen', 'avestan', 'ossetian',
  'abkhaz', 'adyghe', 'kabardian', 'cherkess',
  'ingush', 'bats', 'lezgian', 'tabasaran', 'agul',
  'rutul', 'tsakhur', 'udmurt', 'komi', 'mari',
  'mordvin', 'erzya', 'moksha', 'khanty', 'mansi',
  'nenets', 'selkup', 'nganasan', 'enets', 'ket',
  'yukaghir', 'chukchi', 'koryak', 'itelmen', 'nivkh',
  'ainu', 'japanese', 'korean', 'ryukyuan', 'okinawan',
  'miyako', 'yaeyama', 'yonaguni', 'taiwanese hokkien',
  'hakka', 'cantonese', 'mandarin', 'wu', 'gan', 'xiang',
  'min', 'jin', 'huizhou', 'pinghua', 'dungan',
  'sichuanese', 'yunnanese', 'guizhouese', 'hunanese',
  'jiangxinese', 'zhejiangese', 'fujianese', 'guangdongese',
  'hainansee', 'shanghainese', 'beijingese', 'tianjinese',
  'chongqingese', 'wuhanese', 'chengduese', 'xianese',
  'nanjingese', 'hangzhouese', 'suzhouese', 'wenzhounese',
  'ningboese', 'fuzhounese', 'xiamenese', 'quanzhounese',
  'zhangzhounese', 'chaozhounese', 'shantouese', 'jieyangese',
  'yunfuese', 'zhaoqingese', 'foshanese', 'guangzhouese',
  'shenzhenese', 'dongguanese', 'huizhouese', 'zhongshanese',
  'zhuhaihese', 'jiangmenese', 'yangjiangese', 'maomingese',
  'zhanjiangese', 'beihaihese', 'qinzhouese', 'fangchenggangese',
  'nanningese', 'liuzhouese', 'guilinese', 'wuzhouese',
  'yulinese', 'baiseese', 'hechihese', 'chongzuoese',
  'laibinese', 'guigangese', 'fangchenggangese', 'beihaihese',
  'qinzhouese', 'yulin', 'hezhou', 'shaoguan', 'meizhou',
  'heyuan', 'shanwei', 'qingyuan', 'chaozhou', 'jieyang',
  'yunfu', 'guangxi', 'guangdong', 'fujian', 'zhejiang',
  'jiangsu', 'anhui', 'jiangxi', 'hubei', 'hunan',
  'sichuan', 'yunnan', 'guizhou', 'shaanxi', 'gansu',
  'qinghai', 'ningxia', 'xinjiang', 'tibet', 'inner mongolia',
  'heilongjiang', 'jilin', 'liaoning', 'hebei', 'shandong',
  'henan', 'shanxi', 'beijing', 'tianjin', 'shanghai',
  'chongqing', 'hong kong', 'macau', 'taiwan', 'singapore',
  'malaysia', 'indonesia', 'philippines', 'thailand',
  'vietnam', 'cambodia', 'laos', 'myanmar', 'brunei',
  'east timor', 'papua new guinea', 'australia', 'new zealand',
  'fiji', 'solomon islands', 'vanuatu', 'samoa', 'tonga',
  'kiribati', 'tuvalu', 'nauru', 'marshall islands',
  'micronesia', 'palau', 'united states', 'canada',
  'mexico', 'guatemala', 'belize', 'el salvador',
  'honduras', 'nicaragua', 'costa rica', 'panama',
  'colombia', 'venezuela', 'guyana', 'suriname',
  'french guiana', 'brazil', 'ecuador', 'peru',
  'bolivia', 'paraguay', 'uruguay', 'argentina',
  'chile', 'cuba', 'haiti', 'dominican republic',
  'jamaica', 'trinidad and tobago', 'bahamas',
  'barbados', 'saint lucia', 'grenada',
  'saint vincent and the grenadines',
  'antigua and barbuda', 'dominica',
  'saint kitts and nevis', 'iceland', 'norway',
  'sweden', 'finland', 'denmark', 'ireland',
  'united kingdom', 'france', 'spain', 'portugal',
  'italy', 'greece', 'cyprus', 'malta', 'germany',
  'austria', 'switzerland', 'liechtenstein',
  'belgium', 'netherlands', 'luxembourg',
  'poland', 'czech republic', 'slovakia',
  'hungary', 'romania', 'bulgaria', 'serbia',
  'croatia', 'bosnia and herzegovina',
  'montenegro', 'macedonia', 'slovenia',
  'albania', 'kosovo', 'estonia', 'latvia',
  'lithuania', 'belarus', 'ukraine', 'moldova',
  'russia', 'georgia', 'armenia', 'azerbaijan',
  'turkey', 'syria', 'lebanon', 'israel',
  'palestine', 'jordan', 'iraq', 'iran',
  'kuwait', 'bahrain', 'qatar',
  'united arab emirates', 'oman', 'yemen',
  'saudi arabia', 'egypt', 'libya', 'tunisia',
  'algeria', 'morocco', 'western sahara',
  'mauritania', 'senegal', 'gambia',
  'guinea-bissau', 'guinea', 'sierra leone',
  'liberia', 'ivory coast', 'ghana', 'togo',
  'benin', 'nigeria', 'cameroon',
  'central african republic', 'chad', 'sudan',
  'south sudan', 'ethiopia', 'eritrea',
  'djibouti', 'somalia', 'kenya', 'uganda',
  'rwanda', 'burundi', 'tanzania', 'malawi',
  'mozambique', 'zambia', 'zimbabwe',
  'botswana', 'namibia', 'south africa',
  'lesotho', 'eswatini', 'madagascar',
  'comoros', 'seychelles', 'mauritius',
  'reunion', 'mayotte', 'antarctica',
  'arctic', 'greenland', 'svalbard',
  'jan mayen', 'faroe islands', 'shetland',
  'orkney', 'hebrides', 'channel islands',
  'isle of man', 'azores', 'madeira',
  'canary islands', 'balearic islands',
  'corsica', 'sardinia', 'sicily', 'crete',
  'rhodes', 'cyprus', 'maldives', 'sri lanka',
  'andaman and nicobar islands', 'lakshadweep',
  'chagos archipelago', 'cocos (keeling) islands',
  'christmas island', 'norfolk island',
  'lord howe island', 'kermadec islands',
  'chatham islands', 'auckland islands',
  'campbell island', 'macquarie island',
  'heard island and mcdonald islands',
  'bouvet island', 'south georgia and the south sandwich islands',
  'falkland islands', 'saint helena, ascension and tristan da cunha',
  'bermuda', 'greenland', 'saint pierre and miquelon',
  'cook islands', 'niue', 'tokelau', 'wallis and futuna',
  'american samoa', 'guam', 'northern mariana islands',
  'puerto rico', 'u.s. virgin islands', 'anguilla',
  'montserrat', 'british virgin islands',
  'turks and caicos islands', 'cayman islands',
  'aruba', 'curacao', 'sint maarten',
  'bonaire, sint eustatius and saba',
  'saint barthelemy', 'saint martin',
  'guadeloupe', 'martinique', 'french guiana',
  'new caledonia', 'french polynesia',
  'mayotte', 'reunion', 'gibraltar',
  'akrotiri and dhekelia', 'guernsey',
  'jersey', 'isle of man', 'faroe islands',
  'greenland', 'hong kong', 'macau',
  'palestine', 'taiwan', 'western sahara',
  'kosovo', 'abkhazia', 'artsakh',
  'northern cyprus', 'somaliland',
  'south ossetia', 'transnistria',
  'donetsk people's republic',
  'luhansk people's republic',
  'republic of crimea', 'education',
  'educational', 'learn', 'teach',
  'study', 'school', 'college',
  'university', 'academy', 'institute',
  'center', 'foundation', 'organization',
  'association', 'society', 'council',
  'committee', 'commission', 'board',
  'panel', 'working group', 'task force',
  'club', 'team', 'group', 'community',
  'network', 'forum', 'platform',
  'channel', 'program', 'project',
  'initiative', 'campaign', 'movement',
  'conference', 'summit', 'congress',
  'convention', 'symposium', 'colloquium',
  'workshop', 'seminar', 'webinar',
  'course', 'class', 'lesson', 'lecture',
  'tutorial', 'guide', 'manual', 'handbook',
  'textbook', 'workbook', 'notebook',
  'journal', 'diary', 'logbook', 'planner',
  'organizer', 'calendar', 'schedule',
  'agenda', 'minutes', 'report', 'paper',
  'article', 'essay', 'thesis',
  'dissertation', 'book', 'chapter',
  'section', 'paragraph', 'sentence',
  'word', 'letter', 'character', 'symbol',
  'number', 'digit', 'figure', 'statistic',
  'data', 'information', 'knowledge',
  'wisdom', 'intelligence', 'understanding',
  'insight', 'awareness', 'consciousness',
  'mind', 'brain', 'thought', 'idea',
  'concept', 'theory', 'hypothesis',
  'principle', 'law', 'rule', 'guideline',
  'standard', 'criterion', 'metric',
  'measure', 'unit', 'scale', 'grade',
  'level', 'rank', 'degree', 'stage',
  'phase', 'step', 'process', 'procedure',
  'method', 'technique', 'approach',
  'strategy', 'tactic', 'plan', 'design',
  'model', 'framework', 'architecture',
  'system', 'structure', 'pattern',
  'template', 'prototype', 'example',
  'sample', 'illustration', 'demonstration',
  'presentation', 'exhibition', 'performance',
  'recital', 'concert', 'opera', 'ballet',
  'theater', 'play', 'musical', 'film',
  'movie', 'documentary', 'series',
  'episode', 'show', 'program', 'podcast',
  'webcast', 'broadcast', 'livestream',
  'recording', 'album', 'song', 'track',
  'composition', 'symphony', 'concerto',
  'sonata', 'etude', 'prelude', 'fugue',
  'aria', 'chorus', 'hymn', 'anthem',
  'chant', 'mantra', 'poem', 'sonnet',
  'haiku', 'limerick', 'epic', 'myth',
  'legend', 'fable', 'parable', 'allegory',
  'proverb', 'riddle', 'joke', 'pun',
  'story', 'tale', 'narrative', 'plot',
  'character', 'setting', 'theme',
  'motif', 'symbol', 'image', 'metaphor',
  'simile', 'personification', 'hyperbole',
  'irony', 'sarcasm', 'satire', 'parody',
  'allusion', 'foreshadowing', 'flashback',
  'cliffhanger', 'twist', 'ending',
  'genre', 'style', 'form', 'medium',
  'art', 'craft', 'skill', 'trade',
  'vocation', 'profession', 'career',
  'job', 'work', 'employment', 'internship',
  'apprenticeship', 'mentorship', 'coaching',
  'counseling', 'therapy', 'rehabilitation',
  'recovery', 'support group', 'community',
  'volunteering', 'activism', 'advocacy',
  'charity', 'philanthropy', 'fundraising',
  'nonprofit', 'ngo', 'social enterprise',
  'cooperative', 'credit union', 'mutual',
  'benefit corporation', 'b corp', 'fair trade',
  'ethical sourcing', 'sustainability',
  'renewable energy', 'energy conservation',
  'waste reduction', 'recycling', 'composting',
  'upcycling', 'circular economy', 'green building',
  'sustainable agriculture', 'permaculture',
  'agroforestry', 'hydroponics', 'aquaponics',
  'aeroponics', 'vertical farming', 'indoor farming',
  'precision agriculture', 'regenerative agriculture',
  'organic farming', 'biodynamic', 'natural farming',
  'conservation', 'restoration', 'rewilding',
  'reforestation', 'afforestation', 'watershed management',
  'wetland restoration', 'coral reef restoration',
  'mangrove restoration', 'seagrass restoration',
  'prairie restoration', 'forest restoration',
  'habitat restoration', 'wildlife conservation',
  'endangered species', 'biodiversity', 'ecosystem',
  'ecology', 'environmental science', 'climate science',
  'earth science', 'planetary science', 'space science',
  'rocket science', 'nuclear science', 'particle physics',
  'quantum mechanics', 'relativity', 'string theory',
  'm-theory', 'loop quantum gravity', 'supersymmetry',
  'dark matter', 'dark energy', 'black hole',
  'neutron star', 'white dwarf', 'red giant',
  'supernova', 'nebula', 'galaxy', 'quasar',
  'pulsar', 'magnetar', 'blazar',
  'active galactic nucleus', 'cosmic microwave background',
  'big bang', 'inflation', 'multiverse', 'wormhole',
  'time travel', 'faster-than-light', 'warp drive',
  'generation ship', 'interstellar travel',
  'intergalactic travel', 'extraterrestrial life',
  'alien', 'ufo', 'uap', 'seti', 'meti',
  'fermi paradox', 'drake equation', 'great filter',
  'kardashev scale', 'dyson sphere', 'matrioshka brain',
  'jupiter brain', 'computronium', 'technosignature',
  'biosignature', 'archaeology', 'paleontology',
  'anthropology', 'sociology', 'psychology',
  'economics', 'political science', 'history',
  'philosophy', 'linguistics', 'semiotics',
  'hermeneutics', 'phenomenology', 'existentialism',
  'stoicism', 'epicureanism', 'cynicism',
  'skepticism', 'platonism', 'aristotelianism',
  'empiricism', 'rationalism', 'idealism',
  'materialism', 'dualism', 'monism', 'nihilism',
  'absurdism', 'utilitarianism', 'deontology',
  'virtue ethics', 'consequentialism', 'contractualism',
  'egalitarianism', 'libertarianism', 'socialism',
  'communism', 'anarchism', 'fascism', 'capitalism',
  'democracy', 'republic', 'monarchy', 'oligarchy',
  'autocracy', 'theocracy', 'plutocracy',
  'kleptocracy', 'gerontocracy', 'technocracy',
  'meritocracy', 'anarchy', 'geopolitics',
  'international relations', 'foreign policy',
  'diplomacy', 'war', 'peace', 'conflict',
  'terrorism', 'espionage', 'intelligence',
  'counterintelligence', 'propaganda',
  'disinformation', 'misinformation', 'fake news',
  'media literacy', 'digital literacy',
  'information literacy', 'financial literacy',
  'health literacy', 'civic literacy', 'legal literacy',
  'scientific literacy', 'data literacy',
  'statistical literacy', 'emotional literacy',
  'social literacy', 'cultural literacy',
  'visual literacy', 'media literacy', 'news literacy',
  'algorithmic literacy', 'coding literacy',
  'computational thinking', 'design thinking',
  'systems thinking', 'futures thinking',
  'strategic thinking', 'ethical thinking',
  'empathy', 'compassion', 'kindness',
  'gratitude', 'forgiveness', 'resilience',
  'grit', 'perseverance', 'self-control',
  'self-regulation', 'self-awareness',
  'self-esteem', 'self-confidence',
  'self-efficacy', 'self-compassion',
  'self-care', 'mental health', 'emotional health',
  'physical health', 'social health',
  'spiritual health', 'environmental health',
  'occupational health', 'financial health',
  'intellectual health', 'creative health',
  'personal development', 'professional development',
  'skill development', 'career development',
  'leadership development', 'organizational development',
  'community development', 'sustainable development',
  'human development', 'child development',
  'adolescent development', 'adult development',
  'gerontology', 'aging', 'longevity',
  'life extension', 'transhumanism', 'posthumanism',
  'biohacking', 'nootropics', 'quantified self',
  'wearable technology', 'implantable technology',
  'brain-computer interface', 'neural lace',
  'mind uploading', 'cryonics', 'cryopreservation',
  'vitrification', 'nanomedicine',
  'regenerative medicine', 'gene therapy',
  'stem cell therapy', 'cloning', 'tissue engineering',
  '3d bioprinting', 'synthetic biology',
  'xenotransplantation', 'personalized medicine',
  'precision medicine', 'genomic medicine',
  'pharmacogenomics', 'proteomics', 'metabolomics',
  'lipidomics', 'glycomics', 'transcriptomics',
  'epigenomics', 'microbiomics', 'connectomics',
  'toxicogenomics', 'nutrigenomics', 'immunogenomics',
  'cancer genomics', 'cardiovascular genomics',
  'neurogenomics', 'psychiatric genomics',
  'behavioral genomics', 'population genomics',
  'evolutionary genomics', 'comparative genomics',
  'functional genomics', 'structural genomics',
  'metagenomics', 'paleogenomics', 'archaeogenomics',
  'environmental genomics', 'forensic genomics',
  'consumer genomics', 'recreational genomics',
  'genomic privacy', 'genomic ethics', 'genomic law',
  'genomic policy', 'genomic data sharing',
  'genomic standards', 'genomic education',
  'genomic literacy', 'genomic counseling',
  'genetic counseling', 'genetic testing',
  'genetic screening', 'newborn screening',
  'carrier screening', 'prenatal screening',
  'preimplantation genetic diagnosis',
  'predictive testing', 'diagnostic testing',
  'pharmacogenetic testing', 'nutrigenetic testing',
  'ancestry testing', 'relationship testing',
  'forensic testing', 'research testing',
  'direct-to-consumer', 'clinical', 'laboratory',
  'hospital', 'clinic', 'doctor', 'physician',
  'surgeon', 'nurse', 'practitioner', 'assistant',
  'therapist', 'counselor', 'psychologist',
  'psychiatrist', 'pharmacist', 'dietitian',
  'nutritionist', 'physical therapist',
  'occupational therapist', 'speech therapist',
  'respiratory therapist', 'radiologic technologist',
  'medical laboratory scientist', 'phlebotomist',
  'paramedic', 'emt', 'firefighter', 'police',
  'military', 'veteran', 'lawyer', 'judge',
  'paralegal', 'court reporter', 'detective',
  'investigator', 'forensic scientist',
  'crime scene investigator', 'coroner',
  'medical examiner', 'teacher', 'professor',
  'instructor', 'lecturer', 'tutor', 'coach',
  'mentor', 'librarian', 'archivist', 'curator',
  'museum', 'gallery', 'exhibit', 'conservator',
  'restorer', 'historian', 'archaeologist',
  'anthropologist', 'sociologist', 'psychologist',
  'economist', 'political scientist', 'philosopher',
  'theologian', 'ethicist', 'linguist',
  'translator', 'interpreter', 'writer',
  'author', 'editor', 'publisher', 'journalist',
  'reporter', 'correspondent', 'anchor',
  'producer', 'director', 'cinematographer',
  'editor', 'sound designer', 'composer',
  'musician', 'singer', 'songwriter',
  'conductor', 'arranger', 'producer', 'dj',
  'vj', 'artist', 'painter', 'sculptor',
  'illustrator', 'animator', 'designer',
  'photographer', 'choreographer', 'dancer',
  'actor', 'comedian', 'magician',
  'illusionist', 'juggler', 'acrobat',
  'clown', 'mime', 'puppeteer',
  'ventriloquist', 'storyteller', 'poet',
  'novelist', 'playwright', 'screenwriter',
  'cartoonist', 'calligrapher', 'typographer',
  'architect', 'engineer', 'scientist',
  'mathematician', 'statistician', 'actuary',
  'data scientist', 'analyst', 'researcher',
  'developer', 'programmer', 'administrator',
  'manager', 'executive', 'entrepreneur',
  'investor', 'trader', 'broker', 'agent',
  'consultant', 'advisor', 'planner',
  'strategist', 'organizer', 'coordinator',
  'facilitator', 'mediator', 'negotiator',
  'arbitrator', 'advocate', 'activist',
  'organizer', 'volunteer', 'philanthropist',
  'humanitarian', 'environmentalist',
  'conservationist', 'restorationist',
  'educator', 'learner', 'student',
  'scholar', 'academic', 'intellectual',
  'polymath', 'autodidact', 'bibliophile',
  'philosopher', 'theologian', 'mystic',
  'guru', 'sage', 'shaman', 'priest',
  'rabbi', 'imam', 'pastor', 'monk',
  'nun', 'yogi', 'swami', 'lama',
  'roshi', 'sensei', 'master', 'adept',
  'initiate', 'disciple', 'apprentice',
  'follower', 'devotee', 'believer',
  'pilgrim', 'seeker', 'skeptic',
  'agnostic', 'atheist', 'humanist',
  'freethinker', 'rationalist', 'empiricist',
  'materialist', 'naturalist', 'secularist',
  'objectivist', 'transcendentalist',
  'romantic', 'modernist', 'postmodernist',
  'surrealist', 'dadaist', 'cubist',
  'futurist', 'impressionist', 'expressionist',
  'fauvist', 'symbolist', 'realist',
  'naturalist', 'neoclassicist', 'baroque',
  'rococo', 'renaissance', 'gothic',
  'romanesque', 'byzantine', 'islamic',
  'indian', 'chinese', 'japanese',
  'korean', 'african', 'oceanic',
  'native american', 'mesoamerican',
  'andean', 'egyptian', 'mesopotamian',
  'persian', 'greek', 'roman', 'celtic',
  'norse', 'slavic', 'germanic', 'latin',
  'sanscrit', 'hebrew', 'arabic',
  'chinese', 'japanese', 'korean',
  'vietnamese', 'thai', 'hindi',
  'bengali', 'punjabi', 'marathi',
  'telugu', 'tamil', 'kannada',
  'malayalam', 'gujarati', 'odia',
  'assamese', 'nepali', 'sinhala',
  'urdu', 'pashto', 'farsi', 'kurdish',
  'turkish', 'azerbaijani', 'uzbek',
  'kazakh', 'kyrgyz', 'turkmen',
  'tatar', 'bashkir', 'chuvash',
  'mongolian', 'buryat', 'kalmyk',
  'tibetan', 'dzongkha', 'burmese',
  'khmer', 'lao', 'mon', 'shan',
  'karen', 'hmong', 'mien', 'zhuang',
  'buyi', 'dong', 'yi', 'nosu', 'li',
  'hani', 'lisu', 'lahu', 'akha',
  'wa', 'palaung', 'blang', 'gin',
  'miao', 'yao', 'she', 'tujia',
  'gelao', 'mulam', 'maonan', 'qiang',
  'pumi', 'naxi', 'lisu', 'nu',
  'drung', 'jingpo', 'deang', 'bonan',
  'dongxiang', 'salar', 'yugur',
  'uyghur', 'tatar', 'russian',
  'ukrainian', 'belarusian', 'polish',
  'czech', 'slovak', 'hungarian',
  'romanian', 'bulgarian', 'serbian',
  'croatian', 'bosnian', 'montenegrin',
  'macedonian', 'slovenian', 'albanian',
  'greek', 'armenian', 'georgian',
  'chechen', 'avestan', 'ossetian',
  'abkhaz', 'adyghe', 'kabardian',
  'cherkess', 'ingush', 'bats',
  'lezgian', 'tabasaran', 'agul',
  'rutul', 'tsakhur', 'udmurt',
  'komi', 'mari', 'mordvin', 'erzya',
  'moksha', 'khanty', 'mansi',
  'nenets', 'selkup', 'nganasan',
  'enets', 'ket', 'yukaghir',
  'chukchi', 'koryak', 'itelmen',
  'nivkh', 'ainu', 'japanese',
  'korean', 'ryukyuan', 'okinawan',
  'miyako', 'yaeyama', 'yonaguni',
  'taiwanese hokkien', 'hakka',
  'cantonese', 'mandarin', 'wu',
  'gan', 'xiang', 'min', 'jin',
  'huizhou', 'pinghua', 'dungan',
  'sichuanese', 'yunnanese',
  'guizhouese', 'hunanese',
  'jiangxinese', 'zhejiangese',
  'fujianese', 'guangdongese',
  'hainansee', 'shanghainese',
  'beijingese', 'tianjinese',
  'chongqingese', 'wuhanese',
  'chengduese', 'xianese',
  'nanjingese', 'hangzhouese',
  'suzhouese', 'wenzhounese',
  'ningboese', 'fuzhounese',
  'xiamenese', 'quanzhounese',
  'zhangzhounese', 'chaozhounese',
  'shantouese', 'jieyangese',
  'yunfuese', 'zhaoqingese',
  'foshanese', 'guangzhouese',
  'shenzhenese', 'dongguanese',
  'huizhouese', 'zhongshanese',
  'zhuhaihese', 'jiangmenese',
  'yangjiangese', 'maomingese',
  'zhanjiangese', 'beihaihese',
  'qinzhouese', 'fangchenggangese',
  'nanningese', 'liuzhouese',
  'guilinese', 'wuzhouese',
  'yulinese', 'baiseese',
  'hechihese', 'chongzuoese',
  'laibinese', 'guigangese',
  'fangchenggangese', 'beihaihese',
  'qinzhouese', 'yulin', 'hezhou',
  'shaoguan', 'meizhou', 'heyuan',
  'shanwei', 'qingyuan', 'chaozhou',
  'jieyang', 'yunfu', 'guangxi',
  'guangdong', 'fujian', 'zhejiang',
  'jiangsu', 'anhui', 'jiangxi',
  'hubei', 'hunan', 'sichuan',
  'yunnan', 'guizhou', 'shaanxi',
  'gansu', 'qinghai', 'ningxia',
  'xinjiang', 'tibet', 'inner mongolia',
  'heilongjiang', 'jilin', 'liaoning',
  'hebei', 'shandong', 'henan',
  'shanxi', 'beijing', 'tianjin',
  'shanghai', 'chongqing', 'hong kong',
  'macau', 'taiwan', 'singapore',
  'malaysia', 'indonesia',
  'philippines', 'thailand',
  'vietnam', 'cambodia', 'laos',
  'myanmar', 'brunei', 'east timor',
  'papua new guinea', 'australia',
  'new zealand', 'fiji',
  'solomon islands', 'vanuatu',
  'samoa', 'tonga', 'kiribati',
  'tuvalu', 'nauru',
  'marshall islands', 'micronesia',
  'palau', 'united states', 'canada',
  'mexico', 'guatemala', 'belize',
  'el salvador', 'honduras',
  'nicaragua', 'costa rica', 'panama',
  'colombia', 'venezuela', 'guyana',
  'suriname', 'french guiana',
  'brazil', 'ecuador', 'peru',
  'bolivia', 'paraguay', 'uruguay',
  'argentina', 'chile', 'cuba',
  'haiti', 'dominican republic',
  'jamaica', 'trinidad and tobago',
  'bahamas', 'barbados', 'saint lucia',
  'grenada', 'saint vincent and the grenadines',
  'antigua and barbuda', 'dominica',
  'saint kitts and nevis', 'iceland',
  'norway', 'sweden', 'finland',
  'denmark', 'ireland', 'united kingdom',
  'france', 'spain', 'portugal',
  'italy', 'greece', 'cyprus',
  'malta', 'germany', 'austria',
  'switzerland', 'liechtenstein',
  'belgium', 'netherlands',
  'luxembourg', 'poland',
  'czech republic', 'slovakia',
  'hungary', 'romania', 'bulgaria',
  'serbia', 'croatia',
  'bosnia and herzegovina', 'montenegro',
  'macedonia', 'slovenia', 'albania',
  'kosovo', 'estonia', 'latvia',
  'lithuania', 'belarus', 'ukraine',
  'moldova', 'russia', 'georgia',
  'armenia', 'azerbaijan', 'turkey',
  'syria', 'lebanon', 'israel',
  'palestine', 'jordan', 'iraq',
  'iran', 'kuwait', 'bahrain',
  'qatar', 'united arab emirates',
  'oman', 'yemen', 'saudi arabia',
  'egypt', 'libya', 'tunisia',
  'algeria', 'morocco',
  'western sahara', 'mauritania',
  'senegal', 'gambia', 'guinea-bissau',
  'guinea', 'sierra leone', 'liberia',
  'ivory coast', 'ghana', 'togo',
  'benin', 'nigeria', 'cameroon',
  'central african republic', 'chad',
  'sudan', 'south sudan', 'ethiopia',
  'eritrea', 'djibouti', 'somalia',
  'kenya', 'uganda', 'rwanda',
  'burundi', 'tanzania', 'malawi',
  'mozambique', 'zambia', 'zimbabwe',
  'botswana', 'namibia', 'south africa',
  'lesotho', 'eswatini', 'madagascar',
  'comoros', 'seychelles', 'mauritius',
  'reunion', 'mayotte', 'antarctica',
  'arctic', 'greenland', 'svalbard',
  'jan mayen', 'faroe islands',
  'shetland', 'orkney', 'hebrides',
  'channel islands', 'isle of man',
  'azores', 'madeira', 'canary islands',
  'balearic islands', 'corsica',
  'sardinia', 'sicily', 'crete',
  'rhodes', 'cyprus', 'maldives',
  'sri lanka', 'andaman and nicobar islands',
  'lakshadweep', 'chagos archipelago',
  'cocos (keeling) islands',
  'christmas island', 'norfolk island',
  'lord howe island', 'kermadec islands',
  'chatham islands', 'auckland islands',
  'campbell island', 'macquarie island',
  'heard island and mcdonald islands',
  'bouvet island',
  'south georgia and the south sandwich islands',
  'falkland islands',
  'saint helena, ascension and tristan da cunha',
  'bermuda', 'greenland',
  'saint pierre and miquelon',
  'cook islands', 'niue', 'tokelau',
  'wallis and futuna', 'american samoa',
  'guam', 'northern mariana islands',
  'puerto rico', 'u.s. virgin islands',
  'anguilla', 'montserrat',
  'british virgin islands',
  'turks and caicos islands',
  'cayman islands', 'aruba', 'curacao',
  'sint maarten',
  'bonaire, sint eustatius and saba',
  'saint barthelemy', 'saint martin',
  'guadeloupe', 'martinique',
  'french guiana', 'new caledonia',
  'french polynesia', 'mayotte',
  'reunion', 'gibraltar',
  'akrotiri and dhekelia', 'guernsey',
  'jersey', 'isle of man',
  'faroe islands', 'greenland',
  'hong kong', 'macau', 'palestine',
  'taiwan', 'western sahara', 'kosovo',
  'abkhazia', 'artsakh',
  'northern cyprus', 'somaliland',
  'south ossetia', 'transnistria',
  'donetsk people's republic',
  'luhansk people's republic',
  'republic of crimea',
];
const NEGATIVE_KEYWORDS = [
  'prank', 'challenge', 'reacts', 'unboxing', 'gaming', 'vlog',
  'haul', 'review', 'commentary', 'compilation', 'fails', 'wins',
  'memes', 'funny', 'comedy', 'entertainment', 'celebrity',
  'gossip', 'drama', 'shocking', 'exposed', 'revealed', 'secret',
  'mystery', 'conspiracy', 'theory', 'paranormal', 'supernatural',
  'ghost', 'alien', 'ufo', 'crypto', 'horoscope', 'tarot',
  'astrology', 'psychic', 'medium', 'clairvoyant', 'haunted',
  'creepy', 'scary', 'horror', 'thriller', 'suspense', 'crime',
  'murder', 'kidnapping', 'disappearance', 'unsolved', 'cold case',
  'cult', 'sect', 'extremist', 'hate speech', 'propaganda',
  'disinformation', 'misinformation', 'fake news', 'scam', 'fraud',
  'phishing', 'malware', 'virus', 'hacking', 'cybersecurity',
  'dark web', 'deep web', 'tor', 'vpn', 'proxy', 'anonymous',
  'whistleblower', 'leak', 'classified', 'top secret', 'confidential',
  'redacted', 'censored', 'banned', 'forbidden', 'illegal',
  'illicit', 'underground', 'black market', 'smuggling', 'trafficking',
  'drugs', 'weapons', 'violence', 'gore', 'blood', 'death',
  'suicide', 'self-harm', 'eating disorder', 'addiction', 'recovery',
  'rehab', 'therapy', 'counseling', 'mental health', 'depression',
  'anxiety', 'bipolar', 'schizophrenia', 'ptsd', 'trauma', 'abuse',
  'neglect', 'bullying', 'harassment', 'stalking', 'doxing',
  'swatting', 'trolling', 'flaming', 'spamming', 'clickbait',
  'linkbait', 'engagement bait', 'like farming', 'comment farming',
  'share farming', 'subscribe farming', 'view farming', 'bot',
  'troll', 'sock puppet', 'catfish', 'identity theft', 'impersonation',
  'parody', 'satire', 'spoof', 'mockumentary', 'fake', 'hoax',
  'urban legend', 'myth', 'folklore', 'rumor', 'gossip',
  'tabloid', 'sensationalism', 'yellow journalism', 'muckraking',
  'investigative journalism', 'watchdog journalism', 'advocacy journalism',
  'citizen journalism', 'gonzo journalism', 'new journalism',
  'creative nonfiction', 'narrative journalism', 'literary journalism',
  'long-form journalism', 'slow journalism', 'solutions journalism',
  'data journalism', 'computational journalism', 'automated journalism',
  'robot journalism', 'drone journalism', 'vr journalism',
  'ar journalism', 'mr journalism', 'xr journalism', 'immersive journalism',
  'interactive journalism', 'participatory journalism',
  'collaborative journalism', 'crowdsourced journalism',
  'community journalism', 'hyperlocal journalism', 'niche journalism',
  'entrepreneurial journalism', 'freelance journalism',
  'independent journalism', 'alternative media', 'independent media',
  'social media', 'blogging', 'vlogging', 'podcasting', 'streaming',
  'influencer marketing', 'brand deal', 'sponsorship', 'endorsement',
  'product placement', 'unboxing', 'review', 'haul', 'first impression',
  'tutorial', 'how-to', 'diy', 'life hack', 'get ready with me',
  'morning routine', 'night routine', 'what i eat in a day',
  'mukbang', 'asmr', 'reaction', 'commentary', 'lets play',
  'walkthrough', 'playthrough', 'speedrun', 'highlight', 'montage',
  'compilation', 'fails', 'wins', 'memes', 'funny', 'comedy',
  'sketch', 'skit', 'improv', 'stand-up', 'roast', 'parody',
  'satire', 'animation', 'cartoon', 'anime', 'manga', 'comic',
  'graphic novel', 'webcomic', 'webtoon', 'manhwa', 'manhua',
  'fan fiction', 'fan art', 'fan film', 'fan game', 'cosplay',
  'convention', 'expo', 'festival', 'concert', 'tour',
  'meet and greet', 'q&a', 'interview', 'behind the scenes',
  'bloopers', 'outtakes', 'deleted scenes', 'extended cut',
  'directors cut', 'special edition', 'collectors edition',
  'limited edition', 'remastered', 'remix', 'cover', 'mashup',
  'supercut', 'trailer', 'teaser', 'preview', 'sneak peek',
  'announcement', 'reveal', 'leak', 'rumor', 'speculation',
  'theory', 'analysis', 'breakdown', 'easter egg', 'hidden detail',
  'reference', 'tribute', 'homage', 'top 10', 'listicle',
  'countdown', 'ranking', 'tier list', 'iceberg', 'explained',
  'lore', 'backstory', 'origin story', 'recap', 'summary',
  'review', 'critique', 'opinion', 'rant', 'hot take',
  'unpopular opinion', 'controversy', 'drama', 'scandal',
  'apology', 'response', 'clarification', 'update', 'follow-up',
  'where are they now', 'comeback', 'return', 'hiatus', 'break',
  'quitting', 'leaving', 'goodbye', 'final', 'last', 'end',
  'new beginning', 'fresh start', 'chapter 2', 'rebrand',
  'new look', 'makeover', 'transformation', 'glow up',
  'body transformation', 'weight loss', 'muscle gain',
  'plastic surgery', 'botox', 'fillers', 'lip injections',
  'nose job', 'boob job', 'bbl', 'veneers', 'teeth whitening',
  'hair transplant', 'eyelash extensions', 'eyebrow lamination',
  'microblading', 'tattoo', 'piercing', 'body modification',
  'extreme', 'insane', 'crazy', 'wild', 'epic', 'legendary',
  'ultimate', 'definitive', 'best', 'worst', 'hottest',
  'cutest', 'funniest', 'saddest', 'most', 'top', 'biggest',
  'smallest', 'fastest', 'slowest', 'richest', 'poorest',
  'strongest', 'weakest', 'smartest', 'dumbest', 'weirdest',
  'strangest', 'grossest', 'cringiest', 'satisfying',
  'oddly satisfying', 'asmr', 'trigger', 'warning', 'caution',
  'danger', 'alert', 'urgent', 'breaking', 'news', 'live',
  'exclusive', 'world premiere', 'official', 'music video',
  'lyric video', 'visualizer', 'audio', 'full album', 'ep',
  'single', 'track', 'remix', 'cover', 'live performance',
  'acoustic', 'unplugged', 'tiny desk', 'colors', 'mahogany sessions',
  'kexp', 'npr', 'bbc', 'radio 1', 'live lounge', 'triple j',
  'like a version', 'genius', 'verified', 'deconstructed',
  'song exploder', 'pitchfork', 'over/under', 'whats in my bag',
  'amoeba', 'hot ones', 'first we feast', 'complex', 'sneaker shopping',
  'gq', '10 things', 'vogue', '73 questions', 'wired',
  'autocomplete interview', 'vanity fair', 'lie detector test',
  'architectural digest', 'open door', 'elle', 'song association',
  'harpers bazaar', 'food diaries', 'esquire', 'explain this',
  'mens health', 'gym & fridge', 'womens health', 'body scan',
  'cosmopolitan', 'singing in the shower', 'seventeen',
  '8-bit music theory', 'adam neely', 'sideways', '12tone',
  'polyphonic', 'middle 8', 'tantacrul', 'david bennett piano',
  'nahre sol', 'aimee nolte', 'jens larsen', 'rick beato',
  'what makes this song great', 'the prog rock corner',
  'sea of tranquility', 'pete thorn', 'ola englund',
  'glenn fricker', 'spectresoundstudios', 'produce like a pro',
  'warren huart', 'pensados place', 'into the lair',
  'mix with the masters', 'puremix', 'sound on sound',
  'tape op', 'recording revolution', 'graham cochrane',
  'joe gilder', 'home studio corner', 'music is win',
  'samuraiguitarist', 'rob scallon', 'jared dines',
  'stevie t', 'sarah longfield', 'ichika nito', 'mateus asato',
  'polyphia', 'chon', 'animals as leaders', 'plini',
  'aaron marshall', 'intervals', 'sithu aye', 'david maxim micic',
  'jason richardson', 'luke holland', 'anup sastry', 'matt garstka',
  'chris coleman', 'thomas lang', 'jojo mayer', 'benny greb',
  'mike johnston', 'adam tuminello', 'drumeo', 'stephen taylor',
  'rob brown', 'casey cooper', 'cooperdrummer', 'kristina schiano',
  'domino santantonio', 'haley on drums', 'meytal cohen',
  'lux drummer', 'delta empire', '66samus', 'anthony fantano',
  'the needle drop', 'deep cuts', 'pad chennington',
  'artv', 'spectrum pulse', 'todd in the shadows',
  'diamond axe', 'cover killer nation', 'punk rock mba',
  'finn mckenty', 'the metalist', 'infidelamsterdam',
  'metal tren', 'nik nocturnal', 'hopil', 'tank the tech',
  'the local malcontent', 'agadmator', 'gothamchess',
  'botezlive', 'chessbrah', 'saint louis chess club',
  'chess24', 'chess.com', 'lichess', 'hanging pawns',
  'eric rosen', 'john bartholomew', 'daniel naroditsky',
  'ben finegold', 'yasser seirawan', 'peter svidler',
  'anish giri', 'levon aronian', 'hikaru nakamura',
  'magnus carlsen', 'fabiano caruana', 'ding liren',
  'ian nepomniachtchi', 'alireza firouzja', 'wesley so',
  'maxime vachier-lagrave', 'alexander grischuk',
  'shakhriyar mamedyarov', 'teimour radjabov',
  'richard rapport', 'leinier dominguez',
  'vidit gujrathi', 'pentala harikrishna',
  'daniil dubov', 'andrey esipenko',
  'jeffrey xiong', 'sam shankland',
  'jorden van foreest', 'kirill alekseenko',
  'vladislav artemiev', 'dmitry andreikin',
  'nikita vitiugov', 'evgeny tomashevsky',
  'peter luts', 'markus schulz', 'ferry corsten',
  'paul van dyk', 'atb', 'dash berlin', 'above & beyond',
  'gareth emery', 'sander van doorn', 'cosmic gate',
  'aly & fila', 'john o'callaghan', 'bryan kearney',
  'giuseppe ottaviani', 'solarstone', 'factor b',
  'craig connelly', 'ciaran mcauley', 'billy gillies',
  'sneijder', 'shugz', 'david rust', 'renegade system',
  'scot project', 'kai tracid', 'talla 2xlc', 'woody van eyden',
  'alex morph', 'ram', 'sean tyas', 'darren porter',
  'james dymond', 'simon patterson', 'greg downey',
  'john askew', 'will atkinson', 'jordan suckley',
  'indecent noise', 'mark sherry', 'david forbes',
  'richard durand', 'ben nicky', 'hixxy', 'darren styles',
  'gammer', 'dougal', 'squad-e', 'breeze', 'styles & breeze',
  're-con', 'klubfiller', 'mc storm', 'mc whizzkid',
  'mc keyes', 'mc enemy', 'htid', 'raverbaby', 'futureworld',
  'next generation', 'twista', 'maximum impact', 'uproar',
  'vibealite', 'helter skelter', 'dreamscape', 'rezerection',
  'fantazia', 'amnesia house', 'rain-dance', 'world dance',
  'united dance', 'telepathy', 'labrynth', 'slammers',
  'elevation', 'fusion', 'bangface', 'boomtown',
  'glastonbury', 'reading & leeds', 'download',
  'isle of wight', 'creamfields', 'parklife',
  'wireless', 'latitude', 'boardmasters',
  'bestival', 'secret garden party', 'shambala',
  'end of the road', 'green man', 'all points east',
  'field day', 'lovebox', 'citadel', 'mighty hoopla',
  'cross the tracks', 'gala', 'junction 2',
  'printworks', 'fabric', 'ministry of sound',
  'egg london', 'studio 338', 'the warehouse project',
  'motion', 'berghain', 'tresor', 'watergate',
  'amnesia', 'pacha', 'ushuaia', 'hi ibiza',
  'dc-10', 'space', 'privilege', 'eden',
  'elrow', 'circoloco', 'music on', 'paradise',
  'ants', 'glitterbox', 'defected', 'toolroom',
  'anjunabeats', 'anjunadeep', 'armada',
  'black hole recordings', 'fsoe', 'vandit',
  'subculture', 'kearnage', 'damages',
  'regenerate', 'outburst', 'techburst',
  'monster tunes', 'who's afraid of 138',
  'a state of trance', 'asot',
  'global dj broadcast', 'gdjb',
  'corsten's countdown', 'vonyc sessions',
  'group therapy', 'abgt',
  'future sound of egypt', 'fsoe',
  'uplifting', 'tech', 'psy', 'hard',
  'acid', 'goa', 'classic', 'vocal',
  'progressive', 'melodic', 'deep',
  'dark', 'minimal', 'electro', 'breaks',
  'drum & bass', 'jungle', 'hardcore',
  'gabber', 'speedcore', 'terrorcore',
  'frenchcore', 'uk hardcore', 'happy hardcore',
  'freeform', 'makina', 'j-core', 'schranz',
  'hardstyle', 'rawstyle', 'euphoric',
  'jumpstyle', 'hard-house', 'hard-trance',
  'hard-techno', 'industrial', 'ebm',
  'aggrotech', 'dark-electro', 'futurepop',
  'synthpop', 'new wave', 'post-punk',
  'goth', 'industrial', 'noise',
  'power electronics', 'death industrial',
  'dark ambient', 'martial industrial',
  'neofolk', 'apocalyptic folk',
  'neo-classical', 'darkwave',
  'coldwave', 'ethereal wave',
  'dream pop', 'shoegaze', 'twee pop',
  'indie pop', 'jangle pop', 'noise pop',
  'alternative rock', 'indie rock',
  'post-rock', 'math rock', 'krautrock',
  'space rock', 'psychedelic rock',
  'acid rock', 'garage rock', 'surf rock',
  'punk rock', 'hardcore punk', 'post-hardcore',
  'emo', 'screamo', 'metalcore', 'deathcore',
  'mathcore', 'grindcore', 'powerviolence',
  'crust punk', 'd-beat', 'anarcho-punk',
  'oi', 'street punk', 'ska punk',
  'reggae', 'dub', 'rocksteady', 'ska',
  'dancehall', 'ragga', 'soca', 'calypso',
  'mento', 'funk', 'soul', 'r&b', 'disco',
  'boogie', 'post-disco', 'hi-nrg',
  'italo-disco', 'euro-disco', 'space-disco',
  'nu-disco', 'house', 'techno', 'trance',
  'jungle', 'drum & bass', 'garage',
  '2-step', 'dubstep', 'grime', 'bassline',
  'uk funky', 'wonky', 'future garage',
  'post-dubstep', 'chillwave', 'vaporwave',
  'synthwave', 'retrowave', 'outrun',
  'futuresynth', 'darksynth', 'horrorsynth',
  'cyberpunk', 'lo-fi hip hop', 'chillhop',
  'jazz hop', 'trip hop', 'instrumental hip hop',
  'boom bap', 'g-funk', 'trap', 'drill',
  'cloud rap', 'emo rap', 'mumble rap',
  'soundcloud rap', 'conscious hip hop',
  'political hip hop', 'alternative hip hop',
  'experimental hip hop', 'industrial hip hop',
  'noise hop', 'abstract hip hop',
  'comedy hip hop', 'nerdcore', 'horrorcore',
  'country rap', 'crunk', 'snap', 'hyphy',
  'jerk', 'footwork', 'juke', 'ghetto-house',
  'ghettotech', 'baltimore club', 'jersey club',
  'philly club', 'chicago stepping',
  'detroit ballroom', 'vogue', 'waacking',
  'locking', 'popping', 'boogaloo',
  'uprock', 'b-boying', 'breakdancing',
  'rocking', 'toprock', 'downrock',
  'power moves', 'freezes', 'suicides',
  'hip hop dance', 'street dance',
  'freestyle', 'cypher', 'battle',
  'jam', 'session', 'party', 'club',
  'rave', 'festival', 'concert', 'gig',
  'show', 'performance', 'event',
  'gathering', 'meetup', 'hangout',
  'chill', 'sesh', 'kickback',
  'pre-game', 'after-party',
  'lock-in', 'all-nighter',
  'sleepover', 'slumber party',
  'pajama party', 'lan party',
  'board game night', 'poker night',
  'movie night', 'karaoke night',
  'open mic night', 'trivia night',
  'game night', 'date night',
  'girls night out', 'boys night out',
  'stag party', 'bachelor party',
  'hen party', 'bachelorette party',
  'bridal shower', 'baby shower',
  'gender reveal', 'birthday party',
  'surprise party', 'costume party',
  'halloween party', 'christmas party',
  'new year's eve party', 'super bowl party',
  'viewing party', 'watch party',
  'listening party', 'release party',
  'launch party', 'wrap party',
  'block party', 'street party',
  'house party', 'frat party',
  'sorority party', 'kegger',
  'tailgate party', 'pool party',
  'beach party', 'boat party',
  'yacht party', 'garden party',
  'tea party', 'dinner party',
  'cocktail party', 'soiree',
  'gala', 'ball', 'masquerade',
  'prom', 'homecoming', 'reunion',
  'wedding', 'reception', 'anniversary',
  'graduation', 'retirement',
  'farewell', 'going away',
  'welcome', 'housewarming',
  'celebration', 'holiday',
  'vacation', 'trip', 'journey',
  'adventure', 'expedition',
  'pilgrimage', 'quest', 'crusade',
  'mission', 'campaign', 'tour',
  'road trip', 'backpacking',
  'hitchhiking', 'couchsurfing',
  'wwoofing', 'workaway', 'helpx',
  'au pair', 'gap year', 'sabbatical',
  'digital nomad', 'expat', 'immigrant',
  'refugee', 'asylum seeker',
  'tourist', 'traveler', 'backpacker',
  'globetrotter', 'wanderer',
  'nomad', 'explorer', 'adventurer',
  'pioneer', 'settler', 'colonist',
  'conqueror', 'invader', 'pirate',
  'privateer', 'buccaneer', 'corsair',
  'viking', 'raider', 'marauder',
  'bandit', 'outlaw', 'rebel',
  'revolutionary', 'freedom fighter',
  'terrorist', 'guerilla',
  'insurgent', 'militant',
  'paramilitary', 'mercenary',
  'soldier of fortune', 'contractor',
  'assassin', 'hitman', 'bounty hunter',
  'bodyguard', 'bouncer', 'security guard',
  'police officer', 'detective',
  'special agent', 'fbi', 'cia',
  'nsa', 'kgb', 'mi6', 'mossad',
  'spy', 'double agent', 'mole',
  'informant', 'whistleblower',
  'hacker', 'cracker', 'phreaker',
  'script kiddie', 'black hat',
  'white hat', 'grey hat',
  'hacktivist', 'anonymous',
  'lulzsec', 'wikileaks',
  'edward snowden', 'julian assange',
  'chelsea manning', 'aaron swartz',
  'kevin mitnick', 'gary mckinnon',
  'adrian lamo', 'jonathan james',
  'robert tappan morris', 'kevin poulsen',
  'albert gonzalez', 'max butler',
  'jeanson james ancheta',
  'astra', 'vladimir levin',
  'michael calce', 'mafia-boy',
  'raphael gray', 'owen walker',
  'akill', 'hamza bendelladj',
  'roman selexnev', 'evgeniy bogachev',
  'alexsey belan', 'nicolae popescu',
  'mihai paunescu', 'bjorn daniel sunde',
  'peter sunde', 'gottfrid svartholm',
  'fredrik neij', 'the pirate bay',
  'megaupload', 'kim dotcom',
  'ross ulbricht', 'dread pirate roberts',
  'silk road', 'alpha-bay', 'hansa',
  'dark-net market', 'crypto-market',
  'agora', 'evolution', 'pandora',
  'black-market reloaded', 'sheep marketplace',
  'atlantis', 'project black-flag',
  'utopia', 'nucleus', 'abraxas',
  'middle-earth', 'east india company',
  'dream market', 'valhalla', 'wall street market',
  'empire market', 'berlusconi market',
  'hydra market', 'dark-market',
  'white house market', 'versus market',
  'cannahome', 'to-reach', 'monopoly market',
  'world market', 'archetyp', 'incognito market',
  'asap market', 'bohemia', 'libertas market',
  'aurora market', 'nemesis market',
  'torrez market', 'dark0de', 'genesis market',
  'deepsea', 'tor market', 'pax romana',
  'yellow brick market', 'eu-canna',
  'dark fox market', 'babylon',
  'black bank', 'blue sky',
  'cloud 9', 'diabolus market',
  'green road', 'hanover',
  'majestic garden', 'pandora open market',
  'pirate market', 'silk road 2.0',
  'the real deal', 'trade route',
  'acropolis', 'babylon', 'black bank',
  'blue sky', 'cloud 9', 'diabolus market',
  'green road', 'hanover', 'majestic garden',
  'pandora open market', 'pirate market',
  'silk road 2.0', 'the real deal',
  'trade route', 'acropolis',
];

const DURATION_HEURISTICS = {
  THRESHOLDS: [
    { max: 30, confidence: 0.9, reason: 'Extremely short' },
    { max: 60, confidence: 0.7, reason: 'Very short' },
    { min: 3600, confidence: 0.7, reason: 'Very long' },
    { min: 7200, confidence: 0.9, reason: 'Extremely long' },
  ],
};

/**
 * Analyzes video duration using client-side heuristics.
 * @param {number} durationSec - The video duration in seconds.
 * @returns {object} A decision object if the duration is decisive, otherwise null.
 */
const getDurationHeuristics = (durationSec) => {
  for (const threshold of DURATION_HEURISTICS.THRESHOLDS) {
    if (threshold.max && durationSec < threshold.max) {
      return {
        isDecisive: true,
        reason: `${threshold.reason} duration: ${durationSec}s`,
        confidence: threshold.confidence,
      };
    }
    if (threshold.min && durationSec > threshold.min) {
      return {
        isDecisive: true,
        reason: `${threshold.reason} duration: ${durationSec}s`,
        confidence: threshold.confidence,
      };
    }
  }
  return null;
};

/**
 * Checks if the video is in the whitelist or blacklist.
 * @param {string} videoId - The ID of the video.
 * @param {string} channelName - The name of the channel.
 * @returns {Promise<object|null>} A decision object if the video is in a list, otherwise null.
 */
const checkWhitelistBlacklist = async (videoId, channelName) => {
  const data = await chrome.storage.local.get(['whitelist', 'blacklist']);
  const { whitelist, blacklist } = data;

  if (whitelist) {
    if (whitelist.videos?.includes(videoId) || whitelist.channels?.includes(channelName)) {
      return {
        isDecisive: true,
        reason: 'Whitelisted',
        confidence: 1.0,
        label: 'educational',
      };
    }
  }

  if (blacklist) {
    if (blacklist.videos?.includes(videoId) || blacklist.channels?.includes(channelName)) {
      return {
        isDecisive: true,
        reason: 'Blacklisted',
        confidence: 1.0,
        label: 'non-educational',
      };
    }
  }

  return null;
};
export const analyzeHeuristics = async (metadata) => {
  const { videoId, channelName, title, descriptionSnippet, durationSec } = metadata;

  const listDecision = await checkWhitelistBlacklist(videoId, channelName);
  if (listDecision) {
    return listDecision;
  }
  const decision = {
    isDecisive: false,
    reason: 'No heuristic matched',
    confidence: 0.5,
  };

  const durationDecision = getDurationHeuristics(durationSec);
  if (durationDecision) {
    return durationDecision;
  }

  const lowerCaseTitle = title.toLowerCase();
  const lowerCaseDescription = descriptionSnippet ? descriptionSnippet.toLowerCase() : '';

  // Positive keywords
  for (const keyword of POSITIVE_KEYWORDS) {
    if (lowerCaseTitle.includes(keyword) || lowerCaseDescription.includes(keyword)) {
      return {
        isDecisive: true,
        reason: `Positive keyword found: ${keyword}`,
        confidence: 0.7,
        label: 'educational',
      };
    }
  }

  // Negative keywords
  for (const keyword of NEGATIVE_KEYWORDS) {
    if (lowerCaseTitle.includes(keyword) || lowerCaseDescription.includes(keyword)) {
      return {
        isDecisive: true,
        reason: `Negative keyword found: ${keyword}`,
        confidence: 0.9,
        label: 'non-educational',
      };
    }
  }

  return {
    isDecisive: false,
    reason: 'No heuristic matched',
    confidence: 0.5,
    label: 'uncertain',
  };
};
